import type { Metadata } from "next";
import { Nunito, Jost, Urbanist } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar/Navbar";
import { ClientOnly } from "@/components/ClientOnly";
import { RegisterModal } from "@/components/Modals/RegisterModal";
import { ToasterProvider } from "@/lib/Providers/TosterProvider";
import { Toaster } from "react-hot-toast";

const font = Urbanist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <Toaster />
          <RegisterModal />
          <Navbar />
        </ClientOnly>

        {children}
      </body>
    </html>
  );
}
